language: shell
os: windows
sudo: required
# command to install dependencies-P /c/Python36 /c/Python36/
before_install:
  - rm -r -f /c/Python27
  - wget -O cjhpython.exe -nv https://www.python.org/ftp/python/3.6.4/python-3.6.4.exe 
  - ./cjhpython.exe
  - python -m pip install --upgrade pip
env: PATH=/c/Python36:/c/Python36/Scripts:/c/programdata/chocolatey/lib/python3-x86_32/tools/Scripts:$PATH
install:
  - pip install --upgrade pip
  - export TZ='Asia/Shanghai'
  - git config --global user.name cjh0613
  - git config --global user.email cjhbruce@foxmail.com
  - pip install selenium
  - pip install beautifulsoup4
  - pip install lxml
  - pip install openpyxl
  - pip install pyinstaller
# command to run tests
script:
  - pyinstaller -F 1.py -i "xzxs.ico"
  - cd dist
  - git init
  - git add -A
  - git commit -m "更新网站`date +"% Y-% m-% d % H:% M"`Travis CI Auto Builder "
  - git push -f "https://cjh0613:${TOKEN}@github.com/cjh0613/pyincs2.git" master:dev
#deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  #provider: releases
  # Github oauth token
  #api_key: ${TOKEN}
  # 部署文件路径；对于Android就部署生成的 apk 文件
  #file: ./dist/getQQfriends.exe
  # 避免 Travis CI在部署之前清空生成的APK文件
  #skip_cleanup: true
  #on:
    #all_branches: true
branches:
  only:
    - master
